pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "hsounasellami/student-management:1.0.0"
        MAVEN_CMD = "mvn"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your Git repo
                git url: 'https://github.com/hsounaSellami/student-management.git', branch: 'main'
            }
        }

        stage('Build & Test') {
            steps {
                // Clean and build the project, run tests
                sh "${MAVEN_CMD} clean package"
            }
        }

        stage('Generate JaCoCo Report') {
            steps {
                sh "${MAVEN_CMD} jacoco:report"
            }
            post {
                always {
                    // Archive JaCoCo HTML report
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build Docker image using the JAR generated by Maven
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Docker Hub Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push ${DOCKER_IMAGE}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed. Check the logs for errors."
        }
    }
}
